framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
        failure_transport: failed
        transports:
            ## AMQP TRANSPORT
            event:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                    exchange:
                        name: request-api.event
                    queues:
                        request-api.event: ~
            failed:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 99999999
                options:
                    exchange:
                        name: request-api.failed
                    queues:
                        request-api.failed: ~

            ## DOCTRINE TRANSPORT
            event_outbox:
                dsn: '%env(OUTBOX_TRANSPORT_DSN)%'
                failure_transport: event_outbox_failed
            event_outbox_failed:
                dsn: '%env(OUTBOX_FAILED_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 99999999
            event_outbox_sent:
                dsn: '%env(OUTBOX_SENT_TRANSPORT_DSN)%'

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            event.bus:
                default_middleware:
                    allow_no_handlers: true
                middleware:
                    - doctrine_transaction
                    - App\Infrastructure\Outbox\Middleware\ControlIdempotenceMiddleware
                    - App\Infrastructure\Outbox\Middleware\SendFromOutboxMiddleware
                    - App\Infrastructure\Outbox\Middleware\AddOutboxStampMiddleware


#            SOLUTION ceinture & bretelles
#    on wrap aussi l'envoi au transport outbox_failed dans la transaction
#
#            event.bus:
#                default_middleware: false
#                middleware:
#                    - add_bus_name_stamp_middleware: [ 'outbox.bus' ]
#                    - reject_redelivered_message_middleware
#                    - dispatch_after_current_bus
#                    ## OVERRIDE ##
#                    - doctrine_transaction
#                    ## OVERRIDE ##
#                    - failed_message_processing_middleware

#                    - App\Infrastructure\Middleware\ControlIdempotenceMiddleware
#                    - App\Infrastructure\Middleware\SendFromOutboxMiddleware
#                    - App\Infrastructure\Middleware\AddOutboxStampMiddleware

#                    - send_message
#                    - handle_message