framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
        failure_transport: failed
        transports:
            ## bind discussion-api event queue to request-api exchange
            inbound.request-api.event:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: request-api.event
                    queues:
                        discussion-api.event: ~

            ## AMQP TRANSPORT
            event:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 99999999
                options:
                    auto_setup: false
                    exchange:
                        name: discussion-api.event
                    queues:
                        discussion-api.event: ~
            failed:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 99999999
                options:
                    exchange:
                        name: discussion-api.failed
                    queues:
                        discussion-api.failed: ~

            ## DOCTRINE TRANSPORT
            event_outbox:
                dsn: '%env(OUTBOX_TRANSPORT_DSN)%'
                failure_transport: event_outbox_failed
            event_outbox_failed:
                dsn: '%env(OUTBOX_FAILED_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 99999999
            event_outbox_sent:
                dsn: '%env(OUTBOX_SENT_TRANSPORT_DSN)%'

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            event.bus:
                default_middleware:
                    allow_no_handlers: true
                middleware:
                    - doctrine_transaction
                    - App\Infrastructure\Outbox\Middleware\ControlIdempotenceMiddleware
                    - App\Infrastructure\Outbox\Middleware\SendFromOutboxMiddleware
                    - App\Infrastructure\Outbox\Middleware\AddOutboxStampMiddleware