framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
        failure_transport: failed
        transports:
    ######### À METTRE DANS UN AUTRE SERVICES #########
            request.inbound:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: discussion.event
                    queues:
                        request.inbound: ~
    ###################################################
            event:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                    exchange:
                        name: discussion.event
                    queues:
                        discussion.event: ~
            failed:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 99999999
                options:
                    exchange:
                        name: discussion.failed
                    queues:
                        discussion.failed: ~
            outbox:
                dsn: '%env(OUTBOX_TRANSPORT_DSN)%'
                failure_transport: outbox_failed
            outbox_failed:
                dsn: '%env(OUTBOX_FAILED_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 99999999
            outbox_sent:
                dsn: '%env(OUTBOX_SENT_TRANSPORT_DSN)%'
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            event.bus:
                middleware:
                    - doctrine_transaction
                    - App\Infrastructure\Middleware\OutboxMiddleware

#            SOLUTION ceinture & bretelle
#            event.bus:
#                default_middleware: false
#                middleware:
#                    # Before
#                    - add_bus_name_stamp_middleware: [ 'outbox.bus' ]
#                    - reject_redelivered_message_middleware
#                    - dispatch_after_current_bus
#                    - doctrine_transaction # OVERRIDE
#                    - failed_message_processing_middleware
#                    # Custom Middleware
#                    - App\Infrastructure\Middleware\OutboxMiddleware
#                    # After
#                    - send_message
#                    - handle_message